title: Centre de contrôle
language: fr
target: _blank
color: slate
theme: dark
headerStyle: boxed
statusStyle: dot
hideVersion: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: false
layout:
  Accès rapides:
    style: row
    columns: 3
  Stockage:
    style: row
    columns: 1
  Liens:
    style: row
    columns: 3
